import './globals.css';
import { Inter, Roboto } from 'next/font/google';
import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next -App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <h1>Main Layout</h1>
        {children}
        <Footer />
      </body>
    </html>
  );
}
